version: '3.7'
services:
  aidboxdb:
    image: "healthsamurai/aidboxdb:14.5"
    pull_policy: always
    restart: on-failure:5
    volumes:
    - "./pgdata:/data"
    environment:
      POSTGRES_USER:     "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB:       "${PGDATABASE}"

  aidbox:
    image: "healthsamurai/aidboxone:edge"
    pull_policy: always
    depends_on: ["aidboxdb"]
    restart: on-failure
    ports:
      - "8888:8888"
    env_file:
      - .env
    environment:
      PGHOST: "aidboxdb"
      PGPORT: "5432"
      AIDBOX_PORT: "8888"
      AIDBOX_FHIR_VERSION: "4.0.1"
      AIDBOX_ZEN_PROJECT: "/aidbox-project"
      AIDBOX_ZEN_ENTRY: "core"
      AIDBOX_ZEN_DEV_MODE: "ok"
      AIDBOX_COMPLIANCE: "enabled" # NOTE: remove it when constructor api generates compliant capabilitystatement
    volumes:
      - "./aidbox-project:/aidbox-project"
