version: '3.7'
services:
  aidbox-db:
    image: "${PGIMAGE}"
    ports:
      - "${PGHOSTPORT}:${PGPORT}"
    volumes:
    - "./pgdata:/data"
    environment:
      POSTGRES_USER:     "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB:       "${PGDATABASE}"

  aidbox:
    image: "${AIDBOX_IMAGE}"
    depends_on: ["aidbox-db"]
    links:
      - "aidbox-db:database"
    ports:
      - "${AIDBOX_PORT}:${AIDBOX_PORT}"
    env_file:
      - .env
    environment:
      PGHOST: database
      AIDBOX_ZEN_PROJECT: "/aidbox-project"
      AIDBOX_ZEN_ENTRY: "core"
      AIDBOX_ZEN_DEV_MODE: "enabled"
      AIDBOX_BASE_URL: "http://host.docker.internal:8888"
    volumes:
      - "./aidbox-project:/aidbox-project"
